Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: C:\Vinicius\workspace\aws-lambda-java\HelloWorldFunction
      Runtime: java21
      Architectures:
        - x86_64